In [12]:
import torch
import numpy as np

In [13]:
x = torch.empty(5,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.zeros(2)

tensor([0., 0.])

In [33]:
torch.rand(5,6)

tensor([[0.0195, 0.3847, 0.9592, 0.3144, 0.5852, 0.5276],
        [0.9451, 0.5260, 0.7208, 0.5122, 0.9701, 0.8066],
        [0.7855, 0.0326, 0.4288, 0.8256, 0.8251, 0.9736],
        [0.8675, 0.6573, 0.4700, 0.2886, 0.3396, 0.7870],
        [0.1353, 0.5484, 0.6570, 0.9204, 0.4216, 0.8371]])

In [34]:
l = [13,4]
r = np.array([4,56,7])

In [35]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [36]:
x.size()

torch.Size([5, 4])

In [37]:
type(x)

torch.Tensor

In [38]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.5954, 0.4005],
        [0.6793, 0.1926]])
tensor([[0.9871, 0.6968],
        [0.5637, 0.1491]])


In [39]:
x+y

tensor([[1.5825, 1.0972],
        [1.2430, 0.3417]])

In [40]:
torch.add(x,y)

tensor([[1.5825, 1.0972],
        [1.2430, 0.3417]])

In [41]:
y.add(x)

tensor([[1.5825, 1.0972],
        [1.2430, 0.3417]])

In [42]:
y

tensor([[0.9871, 0.6968],
        [0.5637, 0.1491]])

In [43]:
y.add_(x)  # y에 더한값을 저장

tensor([[1.5825, 1.0972],
        [1.2430, 0.3417]])

In [44]:
y

tensor([[1.5825, 1.0972],
        [1.2430, 0.3417]])

In [45]:
y[1,1] #1행 1열

tensor(0.3417)

In [46]:
y[:,1]  #1열

tensor([1.0972, 0.3417])

In [49]:
x = torch.rand(8,8)
print(x)

tensor([[0.8433, 0.3629, 0.7150, 0.0461, 0.7493, 0.8083, 0.6160, 0.5655],
        [0.6128, 0.1158, 0.1140, 0.7480, 0.5517, 0.5458, 0.2854, 0.9791],
        [0.6752, 0.7555, 0.9299, 0.5186, 0.2889, 0.4892, 0.7273, 0.7479],
        [0.6092, 0.3547, 0.9778, 0.0305, 0.3986, 0.2748, 0.1785, 0.0493],
        [0.3163, 0.9214, 0.2285, 0.2154, 0.7516, 0.6247, 0.8256, 0.3062],
        [0.2104, 0.5130, 0.1606, 0.1923, 0.3668, 0.0309, 0.9914, 0.0048],
        [0.6380, 0.3844, 0.6727, 0.4935, 0.7907, 0.7812, 0.5702, 0.8438],
        [0.1551, 0.0080, 0.2554, 0.7388, 0.0856, 0.8029, 0.0459, 0.4509]])


In [50]:
x.view(64)

tensor([0.8433, 0.3629, 0.7150, 0.0461, 0.7493, 0.8083, 0.6160, 0.5655, 0.6128,
        0.1158, 0.1140, 0.7480, 0.5517, 0.5458, 0.2854, 0.9791, 0.6752, 0.7555,
        0.9299, 0.5186, 0.2889, 0.4892, 0.7273, 0.7479, 0.6092, 0.3547, 0.9778,
        0.0305, 0.3986, 0.2748, 0.1785, 0.0493, 0.3163, 0.9214, 0.2285, 0.2154,
        0.7516, 0.6247, 0.8256, 0.3062, 0.2104, 0.5130, 0.1606, 0.1923, 0.3668,
        0.0309, 0.9914, 0.0048, 0.6380, 0.3844, 0.6727, 0.4935, 0.7907, 0.7812,
        0.5702, 0.8438, 0.1551, 0.0080, 0.2554, 0.7388, 0.0856, 0.8029, 0.0459,
        0.4509])

In [51]:
x.view(4,16)  # 4 * 16 행렬로 표시

tensor([[0.8433, 0.3629, 0.7150, 0.0461, 0.7493, 0.8083, 0.6160, 0.5655, 0.6128,
         0.1158, 0.1140, 0.7480, 0.5517, 0.5458, 0.2854, 0.9791],
        [0.6752, 0.7555, 0.9299, 0.5186, 0.2889, 0.4892, 0.7273, 0.7479, 0.6092,
         0.3547, 0.9778, 0.0305, 0.3986, 0.2748, 0.1785, 0.0493],
        [0.3163, 0.9214, 0.2285, 0.2154, 0.7516, 0.6247, 0.8256, 0.3062, 0.2104,
         0.5130, 0.1606, 0.1923, 0.3668, 0.0309, 0.9914, 0.0048],
        [0.6380, 0.3844, 0.6727, 0.4935, 0.7907, 0.7812, 0.5702, 0.8438, 0.1551,
         0.0080, 0.2554, 0.7388, 0.0856, 0.8029, 0.0459, 0.4509]])

In [52]:
x.view(-1,16)  # -1 = 자동값

tensor([[0.8433, 0.3629, 0.7150, 0.0461, 0.7493, 0.8083, 0.6160, 0.5655, 0.6128,
         0.1158, 0.1140, 0.7480, 0.5517, 0.5458, 0.2854, 0.9791],
        [0.6752, 0.7555, 0.9299, 0.5186, 0.2889, 0.4892, 0.7273, 0.7479, 0.6092,
         0.3547, 0.9778, 0.0305, 0.3986, 0.2748, 0.1785, 0.0493],
        [0.3163, 0.9214, 0.2285, 0.2154, 0.7516, 0.6247, 0.8256, 0.3062, 0.2104,
         0.5130, 0.1606, 0.1923, 0.3668, 0.0309, 0.9914, 0.0048],
        [0.6380, 0.3844, 0.6727, 0.4935, 0.7907, 0.7812, 0.5702, 0.8438, 0.1551,
         0.0080, 0.2554, 0.7388, 0.0856, 0.8029, 0.0459, 0.4509]])

In [53]:
x.view(-1, 4, 4)

tensor([[[0.8433, 0.3629, 0.7150, 0.0461],
         [0.7493, 0.8083, 0.6160, 0.5655],
         [0.6128, 0.1158, 0.1140, 0.7480],
         [0.5517, 0.5458, 0.2854, 0.9791]],

        [[0.6752, 0.7555, 0.9299, 0.5186],
         [0.2889, 0.4892, 0.7273, 0.7479],
         [0.6092, 0.3547, 0.9778, 0.0305],
         [0.3986, 0.2748, 0.1785, 0.0493]],

        [[0.3163, 0.9214, 0.2285, 0.2154],
         [0.7516, 0.6247, 0.8256, 0.3062],
         [0.2104, 0.5130, 0.1606, 0.1923],
         [0.3668, 0.0309, 0.9914, 0.0048]],

        [[0.6380, 0.3844, 0.6727, 0.4935],
         [0.7907, 0.7812, 0.5702, 0.8438],
         [0.1551, 0.0080, 0.2554, 0.7388],
         [0.0856, 0.8029, 0.0459, 0.4509]]])

In [54]:
y = x.numpy()
print(y)

[[0.84331053 0.362922   0.71501863 0.04611647 0.7493175  0.80826044
  0.61600167 0.5654922 ]
 [0.6127926  0.11583292 0.11395371 0.7479887  0.55167913 0.545797
  0.28541595 0.9790671 ]
 [0.6752362  0.7554626  0.92994636 0.51860464 0.28885406 0.4891835
  0.72728777 0.7478626 ]
 [0.60921276 0.35472202 0.97776306 0.03048253 0.398602   0.27475864
  0.17853254 0.04932487]
 [0.31628472 0.9213726  0.22849542 0.21537167 0.7515599  0.62474483
  0.8255992  0.30619705]
 [0.2103762  0.51300627 0.16059077 0.19231182 0.3667547  0.03093642
  0.99141186 0.0047909 ]
 [0.6379982  0.38444746 0.6726969  0.49353433 0.79065114 0.7812256
  0.57018846 0.8437897 ]
 [0.15511578 0.00797361 0.25539887 0.7387524  0.08555603 0.8029334
  0.0458945  0.4509182 ]]


In [55]:
type(y)

numpy.ndarray

In [56]:
x = torch.ones(1)

In [57]:
x

tensor([1.])

In [58]:
x.item()  # tensor안의 값을 숫자 형태로 불러옴

1.0