In [1]:
import torch

In [5]:
x = torch.ones(2,2, requires_grad=True) # x에관한 연산을 추적할 수 있게 함
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [9]:
z = 2*y**2
res = z.mean()

In [10]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [12]:
# d(res)/dx_i = x_i + 1
# res = (z_1 + .. z_4)/4
# z_i = 2 y_i ** 2
# z_i = 2(x_i+1) ** 2 
res.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [14]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
import torch.nn as nn
import torch.nn.functional as F